In [ ]:
-python
    - pythone is a programming paradism means it support functional programming and object 
      oriented programming and also work with procedure oriented programing
- procedure oriented language
    - 

In [ ]:
#syntax for class::
class class_name:
    variables
    methods or functions

In [2]:
print("hi,hello")

hi,hello


In [3]:
8+9

17

In [7]:
class HI:
    a=10
    b=10
    name="apssdc"
    def show():
        print("i am from show() function")

In [9]:
HI.name

'apssdc'

In [10]:
HI.a

10

In [11]:
HI.show

<function __main__.HI.show()>

In [12]:
print(HI.a,HI.b)

10 10


In [13]:
class hi:
    name="apssdc"
    program_name='python'
    def display():
        print("iam from display function")
    def show():
        print("iam from show function")
print(hi.name,hi.program_name)
print(hi.display())        

apssdc python
iam from display function
None


In [14]:
print(hi.display)

<function hi.display at 0x0000009017D7C820>


In [17]:
print(hi.display())

iam from display function
None


In [20]:
def display():
        print("iam from display function")
        print("iam from return statement")
def show():
        print("iam from show function")
print(hi.name,hi.program_name)
print(hi.display())
print(hi.show())

apssdc python
iam from display function
None
iam from show function
None


In [22]:
class hello():
    def display():
        print("iam from display function")
        print("iam from return statement")
    def show():
            print("iam from show function")
print(hello.display())
print(hello.show())
            

iam from display function
iam from return statement
None
iam from show function
None


In [29]:
class HI:
    name="apssdc"
    program_name='python'
    def display(self):
        print("iam from display function")
        print("iam from return")
    def show():
        print("iam from show function")
obj=HI()
print(obj.name,obj.program_name)
print(obj.display())
            

apssdc python
iam from display function
iam from return
None


In [ ]:
### constructor
- constructor:with using object we will call method
- in java : class name should be same as method name
- in python: we will use one special method to define constructor
    init(self)

In [33]:
class HAI:
    def __init__(self,name,roll_no):
        self.name=name
        self.roll_no=roll_no
        print("hi",self.name)
    def dis(self):
        print("ur roll no",self.roll_no)

obj=HAI("rakesh","21A85A0514")
obj.dis()

hi rakesh
ur roll no 21A85A0514


### inheritance
- inheritance something parent to child class

class A:
    #a,b=10,20
class B(A):
    #c,d=40,50

In [38]:
class A:
    a,b=10,20
    def msg():
        print("i am from class A")
class B(A):
    c,d=40,50
    def msg1():
        print("i am from class B")
obj=B
print(obj.c,obj.a)
obj.msg1()
obj.msg()

40 10
i am from class B
i am from class A


In [ ]:
### python libraries for datd science
- organizing,processing,analyzing the huge amount of data
- apply data visulization
- extracting the data from the source
- nearly 20 python libraries are there
###top
    - numpy
    - pandes
    - matplotlib
    
### numpy
    - numpy::(num+py) means numerical data+python
    - it is fundamental package for science computing in python
    - numpy is python library
    - it is used to create multidimentiional arrays for fast operation
    
    

In [ ]:
### how to install numpy
- pip install numpy

In [41]:
### how to import and use numpy package
import numpy as np

In [43]:
#how to find the numpy version
np.__version__

'1.20.3'

In [44]:
#how to create numpy arrays
import numpy as np
a=np.array([1,2,3,4]) #single dimentional number
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [47]:
a2=np.array([[2,3,4],[5,6,8]])
print(a2)
print(type(a2))

[[2 3 4]
 [5 6 8]]
<class 'numpy.ndarray'>


In [48]:
### to know about the shape of the array
a2.shape

(2, 3)

In [49]:
li=[2,3,4,5,'h','i']
print(type(li))
a1=np.array(li)
print(a1)
print(type(a1))

<class 'list'>
['2' '3' '4' '5' 'h' 'i']
<class 'numpy.ndarray'>


In [50]:
ar=np.array([[1,2],[3,4],[5,6]])
print(ar)

[[1 2]
 [3 4]
 [5 6]]


In [51]:
print(ar.dtype)

int32


In [52]:
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [53]:
print(b.shape)

(2, 2)


In [55]:
b.itemsize

4

In [56]:
b.ndim

2

In [57]:
##range
a=np.array(range(10))
print(a)
print(type(a))
print(a.shape)
print(a.size)
b=np.array(range(1,10,2))
print(b)
print(b.ndim)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
10
[1 3 5 7 9]
1


In [ ]:
# range()

In [58]:
# zero array
import numpy as np
a1=np.zeros(3)
a2=np.zeros((2,4),dtype="int64")
print(a1.dtype)
print(a2.dtype)
print(a1)
print(a2)

float64
int64
[0. 0. 0.]
[[0 0 0 0]
 [0 0 0 0]]


In [60]:
# one array
a2=np.ones(3,dtype="int64")
print(a2)
np.ones((6,5),dtype="int64")

[1 1 1]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [61]:
#full array -full(dimentions,specified number)
a=np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [62]:
np.diag(a)

array([7, 7, 7])

In [63]:
np.full(3,100)

array([100, 100, 100])

In [65]:
np.full((3,9),500)

array([[500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500]])

In [67]:
#eye array
np.eye(6,dtype="int64")

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=int64)

In [70]:
n=np.eye(5)
n

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
np.diag(n)

array([1., 1., 1., 1., 1.])

In [73]:
r=np.random.randint(1,10)
r

1

In [74]:
s=np.random.randint(1,10,12).reshape(3,4)
s

array([[7, 6, 8, 3],
       [2, 4, 4, 7],
       [7, 8, 9, 5]])

In [76]:
p=np.random.random((6)).reshape(2,3)
p

array([[0.9382439 , 0.24519006, 0.29994746],
       [0.08151311, 0.9619729 , 0.00783192]])

In [77]:
f=np.random.randn(2,3)
f

array([[ 1.13464416,  0.19862438, -0.73699741],
       [-0.81520682,  0.04608305, -1.0742149 ]])

In [78]:
a=np.random.randint(1,30,(10,3))
a

array([[ 8,  8, 24],
       [ 9,  9, 10],
       [ 3, 12, 29],
       [15, 26, 19],
       [ 3, 10,  2],
       [ 3, 11,  7],
       [ 2, 16,  6],
       [16,  3, 20],
       [12, 24, 20],
       [19, 20, 21]])

In [79]:
a[1:5]

array([[ 9,  9, 10],
       [ 3, 12, 29],
       [15, 26, 19],
       [ 3, 10,  2]])

In [80]:
a[2:,:2]

array([[ 3, 12],
       [15, 26],
       [ 3, 10],
       [ 3, 11],
       [ 2, 16],
       [16,  3],
       [12, 24],
       [19, 20]])

In [81]:
a>10

array([[False, False,  True],
       [False, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [False, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [82]:
a[a>10]

array([24, 12, 29, 15, 26, 19, 11, 16, 16, 20, 12, 24, 20, 19, 20, 21])

In [83]:
a[a>10].sum()

304

In [84]:
a.max()

29

In [85]:
a.min()

2

In [86]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
b=np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [89]:
print(a+b)
print("***********")
print(a-b)
print("_____________")
print(a*b)
print("$$$$$$$$$$$$$$")
print(a%b)
print(np.max(a))
print(np.min(b))

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
***********
[[0 0 0]
 [0 0 0]
 [0 0 0]]
_____________
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
$$$$$$$$$$$$$$
[[0 0 0]
 [0 0 0]
 [0 0 0]]
8
0


C:\Users\Lab\AppData\Local\Temp/ipykernel_5852/2907565790.py:7: RuntimeWarning: divide by zero encountered in remainder
  print(a%b)


In [90]:
#0 to 15---->(3,5)
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [91]:
print(np.mean(a))

7.0


In [92]:
b.dot(a)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118],
       [115, 136, 157, 178, 199]])

In [93]:
a+3

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17]])

In [94]:
a+10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [95]:
np.log2(2)

1.0

In [96]:
np.log([1,2,3])

array([0.        , 0.69314718, 1.09861229])

In [97]:
np.exp(1)

2.718281828459045

In [99]:
np.sin(30)

-0.9880316240928618

In [100]:
np.cos(0)

1.0

In [101]:
np.tan(30)

-6.405331196646276

import

### pandas
-pands is the data science package
- it is used for
    -data manupulation(modification and updatations)
    - data analysis
    - data cleaning(to remove unnecessary data from data sets)
- contains mainly two data strucuters in pandas

In [ ]:
# install pandas
- pip install pandas

In [ ]:
import pandas

In [4]:
import pandas as pd

In [5]:
pd.___version___

AttributeError: module 'pandas' has no attribute '___version___'

In [9]:
s="hi goodmoring to every one".split()
pd.Series(s)

0            hi
1    goodmoring
2            to
3         every
4           one
dtype: object

In [11]:
pd.Series(s,index=[1,2,3,4,5])

1            hi
2    goodmoring
3            to
4         every
5           one
dtype: object

In [12]:
li=[12,'python',12.3]
pd.Series(li,index=['int','str','float'])

int          12
str      python
float      12.3
dtype: object

In [13]:
t=('a','e','i','o','u')
pd.Series(t,index=['v1','v2','v3','v4','v5'])

v1    a
v2    e
v3    i
v4    o
v5    u
dtype: object

In [14]:
dic={'key1':123,'key2':'hello','key3':45.6}
pd.Series(dic)

key1      123
key2    hello
key3     45.6
dtype: object

## data frames

In [17]:
# create data using data frames
d=pd.DataFrame([1,2,3,4,5,])
d

0
0  1
1  2
2  3
3  4
4  5

In [18]:
s='clear but not understand'.split()
pd.DataFrame(s)

0
0       clear
1         but
2         not
3  understand

In [19]:
li=[[1,2,3],[4,5,6]]
pd.DataFrame(li,index=['list1','list2'])

0  1  2
list1  1  2  3
list2  4  5  6

In [ ]:
d={'k1':'h','k2':'e','k3':}

In [ ]:
#creating dataframe using list
dic=('names')

In [ ]:
df1=pd.DataFrame({'n_p':[3,4,5,6],'n_h':[34,53,67,76],})

In [20]:
df1.join(df2)

NameError: name 'df1' is not defined